services:
  postgres-db: 
    image: postgres:latest  # Utilise la dernière version de PostgreSQL
    container_name: us_violent_incidents # Nom du conteneur
    restart: always # Redémarre le conteneur automatiquement en cas de plantage
    environment:  # Variables d'environnement pour la configuration de PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432" # Mapping du port 5432 du conteneur vers le port 5434 de l'hôte
    volumes:
      - pgdata:/var/lib/postgresql # Chemin vers le volume pgdata dans lequel vont être persisté nos données
    networks:
      - pg-network
  bronze:  # Service d'ingestion (extraction et chargement dans la couche Bronze)
    image: bronze
    restart: "no"
    depends_on:
      - postgres-db
    env_file: # Utilisation d'un fichier d'environnement pour les variables sensibles
      - ingest.env
    volumes:
      - ./datasets:/datasets:ro # Monte le répertoire local datasets en lecture seule (ro : read only)
    networks:
      - pg-network
  silver:  # Service de création de la couche Silver (transformation)
    image: silver
    restart: "no"
    depends_on:
      - postgres-db
    env_file: # Utilisation d'un fichier d'environnement pour les variables sensibles (sécurité)
      - etl.env
    networks:
      - pg-network
  gold:  # Service de création de la couche Gold (tables dimensionnelles et tables de faits)
    image: gold
    restart: "no"
    depends_on:
      - postgres-db
    env_file: # Utilisation d'un fichier d'environnement pour les variables sensibles (sécurité)
      - etl.env
    networks:
      - pg-network
      
networks:
  pg-network:
    name: pg-network # force le nom exact (éviter les préfixes automatiques)
    driver: bridge
   
volumes:
  pgdata: {}
